# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mydj.Publisher'),
        ),
    ]
