# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydj', '0002_auto_20160603_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u7b54\u6848')),
                ('score', models.IntegerField(blank=True, verbose_name='\u5206\u6570')),
            ],
            options={
                'ordering': ['score'],
                'verbose_name': '\u7b54\u6848',
                'verbose_name_plural': '\u7b54\u6848',
            },
        ),
        migrations.CreateModel(
            name='ItemAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydj.Answers')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u9898\u76ee')),
                ('parameter', models.CharField(blank=True, max_length=10, verbose_name='\u53c2\u6570')),
                ('answer', models.ManyToManyField(blank=True, to='mydj.Answers', verbose_name='\u7b54\u6848')),
            ],
            options={
                'verbose_name': '\u9898\u76ee',
                'verbose_name_plural': '\u9898\u76ee',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=18, verbose_name='\u5b66\u53f7/\u8eab\u4efd\u8bc1\u53f7')),
                ('score', models.IntegerField(blank=True, verbose_name='\u5f97\u5206')),
                ('item_answer', models.ManyToManyField(blank=True, to='mydj.ItemAnswer', verbose_name='\u7b54\u6848')),
            ],
            options={
                'verbose_name': '\u88ab\u8bd5',
                'verbose_name_plural': '\u88ab\u8bd5',
            },
        ),
        migrations.AddField(
            model_name='itemanswer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydj.Items'),
        ),
    ]
